name: Build Android APK

on:
  push:
    branches: [ "หลัก" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      # สั่ง build เฉพาะ debug และข้ามส่วนที่พัง
      run: ./gradlew assembleDebug -x lint -x kspDebugKotlin

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app-debug
        path: app/build/outputs/apk/debug/*.apk
